language: node_js

node_js:
- "12"

install:
- npm ci

script:
- npm test

before_deploy:
- git config --local user.name "William Wong"
- git config --local user.email "compulim@hotmail.com"
- npx version-from-git --travis

deploy:
- provider: npm
  api_key: $NPM_TOKEN
  edge: true
  email: compulim@hotmail.com
  on:
    branch: master
  skip_cleanup: true
  tag: master

- provider: npm
  api_key: $NPM_TOKEN
  edge: true
  email: compulim@hotmail.com
  on:
    tags: true
  skip_cleanup: true

- provider: releases
  api_key: $GITHUB_TOKEN
  edge: true
  on:
    tags: true
  skip_cleanup: true
