language: node_js

node_js:
- "12"

install:
- npm ci

script:
- npm test

before_deploy:
- git config --local user.name "William Wong"
- git config --local user.email "compulim@hotmail.com"
- npx version-from-git --travis

deploy:
- provider: npm
  api_key:
    secure: aiRht0Sv6d04BYiDVonrii9XYubCmWVLlQqPfsLuwpoonBhgiVEgQOD38cDOJA0uIPn9d9eCjRbc5kM6Mvb02jGqiDu8d6Ra9NK1gyV7+9S6LwnwAj7OOy7SWvXlCagmxlE/1cQdTuloSWHCF+wE4Edc0RgyLoCbA+q8OhpOBdexEURD3/GNcW+8T8r0RBSAjP43/wHVA2xPar9GAt18ie1iSx31SweT6VeWDoifSAqQh9ZCgZSHopZN0rx9O7FfwTJ+qQQDAgTdMQ9Y0q8cFHK5GGvN6CjZ4OEXPn9Uhng/BtWDaaN5V6GurDfscu3bvRwTada+CSOAvhQS2Al+IVmN9ndXrYeeDud9ba4wZ9OfO2VU/WuGz4D1TIIftL/F2wLJL3Hdd2EWyK+DtPTJBV+XVzjP7MBJBeR+D36eFlOyKXAPPbMIdtcEiPYFkGX+AEg9rbZyeMCa/QbZQElb323toz0Kz4xovNhKDa35uT9D0zRbchhWR8ac0KZbta2MdZ0wHMEgCMN1X4xTvVVcGi2boJp9l79kB8oe+BeBG7CRis2BP8smVZrrCgTPvx+JumYumhGRmlzanI2fMPasNhFsbUV7OxU/gTKcKs3eBZMfFVc8twouhIu5NuPb/ZI2Y7X1ONE0iuwG06OCaQ91X87VRX76TfSHanRczUd46Io=
  email: compulim@hotmail.com
  on:
    branch: master
  skip_cleanup: true
  tag: master

- provider: npm
  api_key:
    secure: aiRht0Sv6d04BYiDVonrii9XYubCmWVLlQqPfsLuwpoonBhgiVEgQOD38cDOJA0uIPn9d9eCjRbc5kM6Mvb02jGqiDu8d6Ra9NK1gyV7+9S6LwnwAj7OOy7SWvXlCagmxlE/1cQdTuloSWHCF+wE4Edc0RgyLoCbA+q8OhpOBdexEURD3/GNcW+8T8r0RBSAjP43/wHVA2xPar9GAt18ie1iSx31SweT6VeWDoifSAqQh9ZCgZSHopZN0rx9O7FfwTJ+qQQDAgTdMQ9Y0q8cFHK5GGvN6CjZ4OEXPn9Uhng/BtWDaaN5V6GurDfscu3bvRwTada+CSOAvhQS2Al+IVmN9ndXrYeeDud9ba4wZ9OfO2VU/WuGz4D1TIIftL/F2wLJL3Hdd2EWyK+DtPTJBV+XVzjP7MBJBeR+D36eFlOyKXAPPbMIdtcEiPYFkGX+AEg9rbZyeMCa/QbZQElb323toz0Kz4xovNhKDa35uT9D0zRbchhWR8ac0KZbta2MdZ0wHMEgCMN1X4xTvVVcGi2boJp9l79kB8oe+BeBG7CRis2BP8smVZrrCgTPvx+JumYumhGRmlzanI2fMPasNhFsbUV7OxU/gTKcKs3eBZMfFVc8twouhIu5NuPb/ZI2Y7X1ONE0iuwG06OCaQ91X87VRX76TfSHanRczUd46Io=
  email: compulim@hotmail.com
  on:
    tags: true
  skip_cleanup: true

- provider: releases
  api_key:
    secure: hX6NnBxdG/zHlK5ChfEliyFM0PJ65XEyj/XomUboWWvwO4SLQYVN0gr2xBb4Cz1PP9c4UQG8ImFs1Hbc3IDNxyyuEO0XBqDfMFbjFyj6KaCANx16tIF9Vt3YTDMyKjlyuDQhpq+BKLJhpKQwcQx1rfpv/DxBimxwnw1v6HanZPy4pvsFaeTBKt3mOh/jeErOYkRwxyLA32S0bl0FjcDt24miWIC1G4UgHrsYgkiO3VpXdsIFkA7otdZekx69zRurOIv8UrwySf6UkbsJPV3P3sd5dXOpq462RXxkWPM9Qz27eUptTnx9QSu0+8MBwiqArKzDAXriZyX12MUXqghgZN/vjkcD80itd5bP5mvGZaGeZDiwdi6d28NK6Tzy2hgTWz72YdHrPZWKCFrjGzwy1YEDSXEzyjz5EpvImHtN2EU7u3n9kbBNilPIQmkARpDmGgHhoGL3ow+LHPIsC0IU5yk9ugrUcL0d69pP3P78atzOdE3HRw1za0JxsXI+ITwdGGbnKfTrQy29bkI+e6c0FHDsVU9y2HZqGzb33rCbGALpO7NQJnzyBqEA5xknrBZgf1nLiW7jsO3Vh+oT4XhEHpKuX6K54cxrjb5k2J1+Q3Ta65gai+iBH1tcPWbuzB61zX2zBg2uQ4YlixZ/09e+U3krq7Gffdx57wZVl7ZPxBQ=
  on:
    tags: true
  skip_cleanup: true
